### ISSUE TITLE
Parent node loses child if `replace_with` is used on child

### ISSUE THREAD

**Issue by masonproffitt** [masonproffitt/TexSoup#2]
```python
>>> TexSoup.TexSoup(r'\Sect{\ref{foo}}').find('ref').replace_with('bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/atlas-physics-office/lib/python3.9/site-packages/TexSoup/data.py", line 573, in replace_with
    self.parent.replace(self, *nodes)
  File "/home/user/miniconda3/envs/atlas-physics-office/lib/python3.9/site-packages/TexSoup/data.py", line 597, in replace
    self.expr.remove(child.expr),
  File "/home/user/miniconda3/envs/atlas-physics-office/lib/python3.9/site-packages/TexSoup/data.py", line 838, in remove
    self._assert_supports_contents()
  File "/home/user/miniconda3/envs/atlas-physics-office/lib/python3.9/site-packages/TexSoup/data.py", line 1084, in _assert_supports_contents
    raise TypeError(
TypeError: Command "Sect" has no children. `add_contents` is only validfor: 1. environments like `itemize` and 2. `\item`. Alternatively, you can add, edit, or delete arguments by modifying `.args`, which behaves like a list.
```

**Comment by masonproffitt** [comment]
#9 was a duplicate of this, which was closed by #10
