### ISSUE TITLE
"Command has no children" error in `replace_with()`

### ISSUE THREAD

**Issue by masonproffitt** [masonproffitt/TexSoup#9]
Example:

```python
>>> import TexSoup
>>> ts = TexSoup.TexSoup('\Fig{\ref{fig:alfa_scheme}}')
>>> ts.find('ref').replace_with('2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/atlas/physics-office/src/TexSoup/TexSoup/data.py", line 573, in replace_with
    self.parent.replace(self, *nodes)
  File "/home/user/atlas/physics-office/src/TexSoup/TexSoup/data.py", line 597, in replace
    self.expr.remove(child.expr),
  File "/home/user/atlas/physics-office/src/TexSoup/TexSoup/data.py", line 838, in remove
    self._assert_supports_contents()
  File "/home/user/atlas/physics-office/src/TexSoup/TexSoup/data.py", line 1084, in _assert_supports_contents
    raise TypeError(
TypeError: Command "Fig" has no children. `add_contents` is only validfor: 1. environments like `itemize` and 2. `\item`. Alternatively, you can add, edit, or delete arguments by modifying `.args`, which behaves like a list.
```

**Comment by masonproffitt** [comment]
Closed by #10
